{"errorMessage": "Required parameter name not set", "errorType": "ValueError", "requestId": "0e57a7f2-6664-411b-a046-eaf5f62a9a29", "stackTrace": ["  File \"/var/task/daily_scraper.py\", line 39, in lambda_handler\n    downloader.daily_download_to_db()\n", "  File \"/var/task/arxiv_downloader.py\", line 172, in daily_download_to_db\n    table = dynamodb.Table(self.db_name)\n", "  File \"/var/lang/lib/python3.11/site-packages/boto3/resources/factory.py\", line 528, in create_resource\n    return partial(\n", "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 41, in __init__\n    super().__init__(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/table.py\", line 29, in __init__\n    super().__init__(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/boto3/resources/base.py\", line 125, in __init__\n    raise ValueError(f'Required parameter {identifier} not set')\n"]}